import Head from 'next/head'
import React from "react";
import ss from "../styles/Home.module.scss"
import {applyMiddleware, createStore} from "redux";
import thunk from "redux-thunk";
import rootReducer from "@/sublimates/Redux/reducers/rootReducer";
import {Provider} from "react-redux";
import {withLayoutPages} from "@/hoc/layouts/pages/layout_pages";
import Lineage2 from "@/Components/Lineage2/Lineage2";


/*export const getStaticProps = async () => {
    const res = await fetch('https://api.publicapis.org/entries');
    const data = await res.json();

    return {
        props: data
    };
};*/




function Home() {
    return (
        <>
            <Head>
                <title>Next_laravel_template</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={ss.home}>
                <Lineage2/>
            </main>
        </>
    )
}

// export default withLayoutPages(Home);
export default (Home);