import React from "react";
import ss from "./pleaseVerifyEmail.module.scss";
import {withLayoutPages} from "@/hoc/layouts/pages/layout_pages";
import Head from "next/head";
import Link from "next/link";


const PleaseVerifyEmail = () => {
    return (
        <>
            <Head>
                <title>Next_laravel_template</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={ss.pleaseVerifyEmail_wrapper}>
                <div className={ss.pleaseVerifyEmail}>
                    <div className={`${ss.icon}`}><i className="fa-solid fa-envelope-open-text"></i></div>
                    <div className={`${ss.title}`}>Please verify your email.</div>
                    <div className={`${ss.buttons}`}><Link href={`/`}><div className="btn btn-warning">Continue</div></Link></div>
                </div>
            </div>
        </>
    );
};

export default withLayoutPages(PleaseVerifyEmail);