import React from "react";
import ss from "./success.module.scss";
import {withLayoutPages} from "@/hoc/layouts/pages/layout_pages";
import Link from "next/link";
import Head from "next/head";


const Success = () => {
    return (
        <>
            <Head>
                <title>Next_laravel_template</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           <div className={`${ss.success_wrapper}`}>
               <div className={ss.success}>
                   <div className={`${ss.icon}`}><i className="fa-regular fa-circle-check"></i></div>
                   <div className={`${ss.title}`}>Email verification success!</div>
                   <div className={`${ss.buttons}`}><Link href={`/`}><div className="btn btn-warning">Continue</div></Link></div>
               </div>
           </div>
        </>
    );
};

export default withLayoutPages(Success);